%%{init: {'flowchart': {'curve': 'linear'}}}%%
graph TD;
    __start__([<p>__start__</p>]):::first
    splitTask(splitTask)
    processSubTask_1("processSubTask (实例1)"):::parallel
    processSubTask_2("processSubTask (实例2)"):::parallel
    processSubTask_3("processSubTask (实例3)"):::parallel
    mergeResults(mergeResults)
    __end__([<p>__end__</p>]):::last
    __start__ --> splitTask;
    splitTask -.-> processSubTask_1;
    splitTask -.-> processSubTask_2;
    splitTask -.-> processSubTask_3;
    processSubTask_1 --> mergeResults;
    processSubTask_2 --> mergeResults;
    processSubTask_3 --> mergeResults;
    mergeResults --> __end__;
    classDef default fill:#f2f0ff,line-height:1.2;
    classDef first fill-opacity:0;
    classDef last fill:#bfb6fc;
    classDef parallel fill:#e0f2fe,stroke:#0284c7,line-height:1.2;
